# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaFtfPU105M3PPLso2-UmGHakSeOrOzd
"""

# ==============================
# TASK 4: SALES PREDICTION
# ==============================

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Upload Dataset
uploaded = files.upload()

# Read Dataset
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

# Display Dataset
print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

# Statistical Summary
print("\nSummary Statistics:")
print(df.describe())

# ==============================
# DATA VISUALIZATION
# ==============================

sns.pairplot(df)
plt.show()

# Correlation Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# ==============================
# FEATURE SELECTION
# ==============================

# Advertising dataset columns:
# TV, Radio, Newspaper, Sales

X = df[['TV', 'Radio', 'Newspaper']]
y = df['Sales']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# ==============================
# MODEL TRAINING
# ==============================

model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# ==============================
# MODEL EVALUATION
# ==============================

print("\nModel Performance")

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# ==============================
# ACTUAL vs PREDICTED
# ==============================

results = pd.DataFrame({
    'Actual Sales': y_test,
    'Predicted Sales': y_pred
})

print("\nSample Predictions:")
print(results.head())

plt.figure(figsize=(8,5))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted Sales")
plt.show()

# ==============================
# FUTURE SALES PREDICTION
# ==============================

# Example:
tv = 230
radio = 37
newspaper = 69

future_sales = model.predict([[tv, radio, newspaper]])

print("\nPredicted Future Sales:")
print(future_sales[0])