# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRE56LYuUawjI5kYl_GIOEmAycwYu137
"""

import os
print(os.listdir())

['Unemployment in India.csv']

TASK 2: UNEMPLOYMENT ANALYSIS
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
print("First 5 Rows:")
print(df.head())
print("\nDataset Information:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())
print("\nStatistical Summary:")
print(df.describe())
df.columns = df.columns.str.strip()
print("\nColumn Names:")
print(df.columns)
rate_col = [col for col in df.columns if "Unemployment Rate" in col][0]
plt.figure(figsize=(8,5))
sns.histplot(df[rate_col], kde=True)
plt.title("Distribution of Unemployment Rate")
plt.show()
region_col = [col for col in df.columns if "Region" in col][0]
avg_rate = df.groupby(region_col)[rate_col].mean()
plt.figure(figsize=(12,6))
avg_rate.sort_values().plot(kind='bar')
plt.title("Average Unemployment Rate by Region")
plt.ylabel("Unemployment Rate (%)")
plt.show()
date_col = [col for col in df.columns if "Date" in col][0]
df[date_col] = pd.to_datetime(df[date_col])
monthly_rate = df.groupby(
    df[date_col].dt.to_period('M')
)[rate_col].mean()
plt.figure(figsize=(12,5))
monthly_rate.plot()
plt.title("Monthly Unemployment Trend")
plt.xlabel("Month")
plt.ylabel("Unemployment Rate (%)")
plt.grid()
plt.show()
covid_data = df[df[date_col] >= '2020-03-01']
plt.figure(figsize=(12,5))
plt.plot(covid_data[date_col],
         covid_data[rate_col])
plt.title("Impact of COVID-19 on Unemployment")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.grid()
plt.show()
numeric_df = df.select_dtypes(include=['number'])
plt.figure(figsize=(8,6))
sns.heatmap(numeric_df.corr(),
            annot=True,
            cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()
print("\nKEY INSIGHTS")
print("1. Unemployment rates changed significantly over time.")
print("2. COVID-19 caused a noticeable increase in unemployment.")
print("3. Some regions experienced higher unemployment than others.")
print("4. Trend analysis can support economic policy decisions.")
print("5. Visualization helps identify patterns and seasonal changes.")

"""# New Section"""